### PR TITLE
Initial optimization

### PR DESCRIPTION
**Pull request by syohex**
This is related to #4.
CC: @TatriX

### CODE REVIEW

**Comment by TatriX** [comment]
I'm working on the `kite-mini` package and I want to add sourcemap support to the repl.
When chrome debugger tells me that he parsed a script he also gives me a sourcemap url.
When I'm getting a `Console.added` message I'd like to use mapped location so I need a parsed sourcemap (`sourcemap-original-position-for` actually) 

I'm not sure if I should lazy load sourcemaps or `emacs-sourcemap` should lazy parse it's mappings. What do you think?

**Comment by TatriX** [comment]
I guess sourcemap shoudn't lazy parse mappings so user will get long creation of the sourcemap and not long first call to the `sourcemap-original-position-for` etc.

**Comment by TatriX** [comment]
I've tested this branch and implemented lazy load for `kite-mini`. Parsing of the large sourcemaps (more than 40000 lines) is dead slow. These big sourcemap generated for lib bundles so I hope I could manage it on my side.

Thank you!

**Comment by syohex** [comment]
```lisp
(defvar test-input
"{
  \"version\": 3,
  \"file\": \"min.js\",
  \"names\": [\"bar\", \"baz\", \"n\"],
  \"sources\": [\"one.js\", \"two.js\"],
  \"sourceRoot\": \"http://example.com/www/js/\",
  \"mappings\": \"CAAC,IAAI,IAAM,SAAUA,GAClB,OAAOC,IAAID;CCDb,IAAI,IAAM,SAAUE,GAClB,OAAOA\"
}")

(setq sourcemap (sourcemap-from-string test-input))
(benchmark 1000 '(sourcemap-original-position-for sourcemap :line 2 :column 28))
```

Micro benchmark between original version and optimize version(Change data structure and use binary search instead of linear search)

```
Original: Elapsed time: 0.985985s (0.510061s in 65 GCs)
Optimized: Elapsed time: 0.097774s (0.043636s in 3 GCs) ;; 10 times faster
```

**Comment by syohex** [comment]
Emacs Lisp is slow language. You should write/use sourcemap decoder written in fast language if you need more speed.

**Pull request merged**
